#!/bin/ash

# print message with the result of a command
printf "My Docker images ip $(hostname -i)\n"
printf "I have been called with those args:\n"
# print all arg passed
printf -- "- '\x1b[31m%s\x1b[00m'\n" $@

# if file /var/www/html/index.html is NOT found
if [ ! -f /var/www/html/index.html ]; then
	printf "Pyton3: init\n"

	# if folder /var/www/html is NOT found then create it
	[ ! -d /var/www/html ] && mkdir -p /var/www/html

	# copy file on needed location
	cp /run/index.html /var/www/html/index.html

	# remove tmp file
	rm -rf /run/index.html
else
	printf "Pyton3: init skipped\n"
fi

# Putting an `exec $@` at the end is very usefull as it allow you to execute whatever
# you wan't after the exec state, this is possible with proper ENTRYPOINT and
# CMD instruction in the Dockerfile
exec $@
